### ISSUE TITLE
Add a way to steal a feesh randomly

### ISSUE THREAD

**Issue by vekst** [Snaptraks/HatBot#19]
tl;dr something such as !feesh steal random

Basically don't know who to steal from anymore, and I think it would be entertaining if there was a command that picked someone at random.

**Comment by Snaptraks** [comment]
Fair point! I just don't know how to make it on a technical point. ie `feesh steal random` would actually be a subcommand of `feesh steal`, but since the latter takes an argument (the `target`) it would mess things up I'm pretty sure. Maybe a `feesh randomsteal` could work.

**Comment by MrOutWeb** [comment]
Random thought, would it be possible to add options like one does in linux (eg: -v)

**Comment by Snaptraks** [comment]
Yes and no. For `feesh steal` the way the library works is that the argument sent to the function is converted into a `discord.Member` object, and the order of the arguments are very important. Having an option flag (-v for example) will be treated as an argument and attempted to be converted to a `discord.Member` object, which will obviously fail.

**Comment by Snaptraks** [comment]
I thought of a way to enable random feesh stealing and giving. A new command !feesh random that takes a subcommand name as argument, like !feesh random steal, and would call the provided subcommand with a random member from the server. How would that sound?
