### ISSUE TITLE
Rework datetimes in Birthday Cog

### ISSUE THREAD

**Issue by MrOutWeb** [Snaptraks/HatBot#32]
The Birthday cog autofires the Birthday event at Midnight GMT the day after the person's Birthday. Even on the latest possible timezone (GMT+12) that still only causes the event to fire at midday on the day. The birthday cog should be reworked so that the event fires earlier. I would recommend standardising based on Midday GMT so the event guaranteed fires on the day in all timezones (there may be potential hiccups in IDL regions (GMT+-12), but it would significantly improve the timings).

Another option would be allowing users to set a timezone, though that would require a lot more work.

**Comment by Snaptraks** [comment]
A fix is in testing, so far so good!

**Comment by Snaptraks** [comment]
I think it's working now. Closing the issue
